export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/pizzaIcon.png"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/pizza.png"),
      description: "Hot and spicy pizzas",
      lng: 19.05659,
      lat: 47.49506,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/pizza.png"),
      description: "Hot and spicy pizzas",
      lng: 19.05659,
      lat: 47.49506,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/pizza.png"),
      description: "Hot and spicy pizzas",
      lng: 19.05659,
      lat: 47.49506,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
  ],
};
export const featured2 = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Simons Burger",
      description: "Serving high quality smash burgers, fries and shakes.",
      lng: 0,
      lat: 0,
      address: "Vitkovics Mihály utca 8. 1052 Budapest",
      stars: 5,
      reviews: "string",
      category: "",
      dishes: [],
    },
    {
      id: 2,
      name: "Simons Burger",
      image:
        "https://imageproxy.wolt.com/menu/menu-images/634e6ee7874ccb7da322de86/1cc53cc4-c432-11ed-9d8c-aa256872df74_smallcheeseburger.jpeg",
      description: "Serving high quality smash burgers, fries and shakes.",
      lng: 0,
      lat: 0,
      address: "Vitkovics Mihály utca 8. 1052 Budapest",
      stars: 5,
      reviews: "string",
      category: "",
      dishes: [],
    },
  ],
};
